server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DB_NAME
    username: postgres
    password: YOUR_PASSWORD
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true